### ISSUE TITLE
Esta condición deberia validar tambien que los dias no sean menor o igual a 0

### ISSUE THREAD

**Issue by AlexanderST01** [Sduran-19/Registro_Prioridades#1]
https://github.com/Sduran-19/Registro_Prioridades/blob/45ccbfb4de63f95cdd288abd6279d4c52fb1d4bb/app/src/main/java/edu/ucne/registro_prioridades/MainActivity.kt#L139

**Comment by Sduran-19** [comment]
Condición agregada
